//
//  PDInputDomain.h
//  PonyDebuggerDerivedSources
//
//  Generated on 1/28/13
//
//  Licensed to Square, Inc. under one or more contributor license agreements.
//  See the LICENSE file distributed with this work for the terms under
//  which Square, Inc. licenses this file to you.
//

#import <PonyDebugger/PDObject.h>
#import <PonyDebugger/PDDebugger.h>
#import <PonyDebugger/PDDynamicDebuggerDomain.h>


@protocol PDInputCommandDelegate;

@interface PDInputDomain : PDDynamicDebuggerDomain 

@property (nonatomic, assign) id <PDInputCommandDelegate, PDCommandDelegate> delegate;

@end

@protocol PDInputCommandDelegate <PDCommandDelegate>
@optional

// Dispatches a key event to the page.
// Param type: Type of the key event.
// Param modifiers: Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
// Param timestamp: Time at which the event occurred. Measured in UTC time in seconds since January 1, 1970 (default: current time).
// Param text: Text as generated by processing a virtual key code with a keyboard layout. Not needed for for <code>keyUp</code> and <code>rawKeyDown</code> events (default: "")
// Param unmodifiedText: Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling (default: "").
// Param keyIdentifier: Unique key identifier (e.g., 'U+0041') (default: "").
// Param windowsVirtualKeyCode: Windows virtual key code (default: 0).
// Param nativeVirtualKeyCode: Native virtual key code (default: 0).
// Param macCharCode: Mac character code (default: 0).
// Param autoRepeat: Whether the event was generated from auto repeat (default: false).
// Param isKeypad: Whether the event was generated from the keypad (default: false).
// Param isSystemKey: Whether the event was a system key event (default: false).
- (void)domain:(PDInputDomain *)domain dispatchKeyEventWithType:(NSString *)type modifiers:(NSNumber *)modifiers timestamp:(NSNumber *)timestamp text:(NSString *)text unmodifiedText:(NSString *)unmodifiedText keyIdentifier:(NSString *)keyIdentifier windowsVirtualKeyCode:(NSNumber *)windowsVirtualKeyCode nativeVirtualKeyCode:(NSNumber *)nativeVirtualKeyCode macCharCode:(NSNumber *)macCharCode autoRepeat:(NSNumber *)autoRepeat isKeypad:(NSNumber *)isKeypad isSystemKey:(NSNumber *)isSystemKey callback:(void (^)(id error))callback;

// Dispatches a mouse event to the page.
// Param type: Type of the mouse event.
// Param x: X coordinate of the event relative to the main frame's viewport.
// Param y: Y coordinate of the event relative to the main frame's viewport. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
// Param modifiers: Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
// Param timestamp: Time at which the event occurred. Measured in UTC time in seconds since January 1, 1970 (default: current time).
// Param button: Mouse button (default: "none").
// Param clickCount: Number of times the mouse button was clicked (default: 0).
- (void)domain:(PDInputDomain *)domain dispatchMouseEventWithType:(NSString *)type x:(NSNumber *)x y:(NSNumber *)y modifiers:(NSNumber *)modifiers timestamp:(NSNumber *)timestamp button:(NSString *)button clickCount:(NSNumber *)clickCount callback:(void (^)(id error))callback;

@end

@interface PDDebugger (PDInputDomain)

@property (nonatomic, readonly, strong) PDInputDomain *inputDomain;

@end
